export const australianCities = [
    {
        name: "Sydney",
        state: "New South Wales",
        population: 5500000,
        latitude: -33.868,
        longitude: 151.207,
        description: "Australia's most populous city and economic hub",
    },
    {
        name: "Melbourne",
        state: "Victoria",
        population: 5350000,
        latitude: -37.814,
        longitude: 144.963,
        description: "Cultural capital known for coffee culture",
    },
    {
        name: "Brisbane",
        state: "Queensland",
        population: 2780000,
        latitude: -27.468,
        longitude: 153.028,
        description: "Gateway to tropical north Queensland",
    },
    {
        name: "Perth",
        state: "Western Australia",
        population: 2310000,
        latitude: -31.952,
        longitude: 115.861,
        description: "Isolated mining and business center",
    },
    {
        name: "Adelaide",
        state: "South Australia",
        population: 1470000,
        latitude: -34.929,
        longitude: 138.599,
        description: "City of Churches with Mediterranean climate",
    },
    {
        name: "Canberra",
        state: "Australian Capital Territory",
        population: 367752,
        latitude: -35.283,
        longitude: 149.128,
        description: "Planned national capital",
    },
    {
        name: "Darwin",
        state: "Northern Territory",
        population: 174728,
        latitude: -12.480556,
        longitude: 130.983063,
        description: "Tropical gateway with wet/dry seasons",
    },
    {
        name: "Gold Coast",
        state: "Queensland",
        population: 640778,
        latitude: -28.0,
        longitude: 153.431,
        description: "Famous beach tourist destination",
    },
    {
        name: "Newcastle",
        state: "New South Wales",
        population: 508437,
        latitude: -32.93,
        longitude: 151.78,
        description: "Industrial port city north of Sydney",
    },
    {
        name: "Wollongong",
        state: "New South Wales",
        population: 280153,
        latitude: -34.424,
        longitude: 150.893,
        description: "Steel industry and university city",
    },
];
