// Files shared by the production copy step and the development static server.
module.exports = [
    { from: "src/static/favicon.ico", to: "" },
    { from: "src/static/webgl-intel.html", to: "" },
    { from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/Shale.csv", to: "" },
    { from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/Density.csv", to: "" },
    {
        from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/Resistivity.csv",
        to: "",
    },
    {
        from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/PoreSpace.csv",
        to: "",
    },
    { from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/Sonic.csv", to: "" },
    { from: "src/components/Examples/FeaturedApps/ShowCases/OilAndGasDashboard/Data/Texture.csv", to: "" },
    {
        from: "src/components/Examples/Charts2D/PolarCharts/PolarUniformHeatmapUltrasound/heatmap_data.csv",
        to: "",
    },
    { from: "src/server/vanillaDemo/common.js", to: "" },
    { from: "node_modules/scichart/_glue/scichart.browser.mjs", to: "" },
    { from: "node_modules/scichart/_wasm/", to: "" },
    { from: "sitemap.xml", to: "" },
    { from: process.env.NOINDEX ? "robotsNoIndex.txt" : "robots.txt", to: "robots.txt" },
    { from: "src/server/Data/geojson/australia.json", to: "" },
    { from: "src/server/Data/geojson/africa.json", to: "" },
    { from: "src/server/Data/geojson/world.json", to: "" },
    { from: "src/server/Data/geojson/usaStates.json", to: "" },
    { from: "src/server/Data/geoJsonConverted/australiaConverted.json", to: "" },
    { from: "src/server/Data/geoJsonConverted/africaConverted.json", to: "" },
    { from: "src/server/Data/geoJsonConverted/worldConverted.json", to: "" },
    { from: "src/server/Data/geoJsonConverted/europeConverted.json", to: "" },
    { from: "src/server/Data/orderBook/LTCUSDT_OHLC.csv", to: "" },
    { from: "src/server/Data/orderBook/orderbook_levels.csv", to: "" },
    { from: "src/server/Data/earthquakes/earthquakes-23k.csv", to: "" },
];
